apiVersion: v1
kind: Secret
metadata:
  name: flarum
  namespace: flarum
  labels:
    app: flarum
type: Opaque
data:
  mariadb-root-password: "{{ "MARIADB_ROOT_PASSWORD" | env | base64 }}"
  mariadb-password: "{{ "MARIADB_PASSWORD" | env | base64 }}"
