apiVersion: v1
kind: Service
metadata:
  name: mariadb
  namespace: flarum
  labels:
    app: flarum
    component: db
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "9104"
spec:
  type: ClusterIP
  ports:
  - name: mysql
    port: 3306
    targetPort: mysql
  - name: metrics
    port: 9104
    targetPort: metrics
  selector:
    app: flarum
    component: db
